# This will be the files for the github actions

name: Django CI/CD

# Trigger this workflow on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Pulls down your code to the runner

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Define the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      run: |
        python manage.py test  # Run Django tests
