# This will be the file for the GitHub Actions workflow
name: Build and Push a Docker Image  # The name of the workflow for easy identification

# Trigger this workflow on push or pull request to the main branch
on:
  push:
    branches: [ "master" ]  # Triggers the workflow when there is a push to the 'master' branch
  pull_request:
    branches: [ "master" ]  # Triggers the workflow when there is a pull request to the 'master' branch

# Define the jobs to run in the workflow
jobs:
  build-and-push:  # The name or type of the job
    runs-on: ubuntu-latest  # The job will run on the latest available Ubuntu runner environment

    steps:  # List of steps to be executed in the job
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the code from the repository to the runner, so it can be used in the next steps

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  # Logs into Docker Hub to authenticate and push images
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Fetches the Docker Hub username from GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Fetches the Docker Hub password from GitHub secrets

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/booster-app:latest .  # Builds the Docker image using the Dockerfile in the repository. The image is tagged with the Docker Hub username and "booster-app:latest".

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/booster-app:latest  # Pushes the built Docker image to Docker Hub with the tag "latest"

